version: '3'

tasks:
  init:
    desc: Initialize Terraform
    cmds:
      - terraform init

  plan:
    desc: Run terraform plan
    cmds:
      - terraform plan

  apply:
    desc: Apply the Terraform configuration
    cmds:
      - terraform apply -auto-approve

  destroy:
    desc: Destroy the Terraform-managed infrastructure
    cmds:
      - terraform destroy -auto-approve

  all:
    desc: Run init, plan, and apply
    cmds:
      - task: init
      - task: plan
      - task: apply

  setup-nomad-consul:
    desc: Configure workload identity between Nomad and Consul (run in both clusters)
    dir: consul-nomad-peering
    cmds:
      - nomad setup consul -y

  create-namespace:
    desc: Create Nomad namespace 'ingress' for API Gateway (only in primary cluster)
    dir: consul-nomad-peering
    cmds:
      - |
        nomad namespace apply \
          -description "namespace for Consul API Gateways" \
          ingress

  create-binding-rule:
    desc: Create ACL binding rule for API Gateway (only in primary cluster)
    dir: consul-nomad-peering
    cmds:
      - |
        consul acl binding-rule create \
          -method 'nomad-workloads' \
          -description 'Nomad API gateway' \
          -bind-type 'templated-policy' \
          -bind-name 'builtin/api-gateway' \
          -bind-vars 'Name=${value.nomad_job_id}' \
          -selector '"nomad_service" not in value and value.nomad_namespace==ingress'

  configure-primary-cluster:
    desc: Full setup for primary cluster (workload identity + namespace + binding rule)
    cmds:
      - task: setup-nomad-consul
      - task: create-namespace
      - task: create-binding-rule

  deploy-api-gw:
    desc: Deploy API Gateway job
    dir: consul-nomad-peering
    cmds:
      - nomad job run api-gw.nomad.hcl

  deploy-tgw:
    desc: Deploy TGW job
    dir: consul-nomad-peering
    cmds:
      - nomad job run tgw.nomad.hcl

  register-httproute:
    desc: Register HTTPRoute configuration
    dir: consul-nomad-peering
    cmds:
      - consul config write httproute.hcl

  register-listener:
    desc: Register listener configuration
    dir: consul-nomad-peering
    cmds:
      - consul config write listener.hcl

  deploy-fake-service:
    desc: Deploy fake service in cluster2
    dir: consul-nomad-peering/demo-fake-service
    cmds:
      - nomad job run fake-service.nomad.hcl

  deploy-all:
    desc: Deploy all Nomad and Consul workloads
    cmds:
      - task: deploy-api-gw
      - task: deploy-tgw
      - task: register-httproute
      - task: register-listener
      - task: deploy-fake-service

  destroy-all:
    desc: Stop all Nomad jobs and remove Consul configs
    dir: consul-nomad-peering
    cmds:
      - nomad job stop -purge api-gw || true
      - nomad job stop -purge tgw || true
      - nomad job stop -purge fake-service || true
      - consul config delete -kind httproute -name api-gw || true
      - consul config delete -kind listener -name api-gw || true

  delete-intentions:
    desc: Delete all Consul intentions
    cmds:
      - consul intention list | tail -n +2 | awk '{print "consul intention delete " $1 " " $3}' | bash

