# crpsul-east-values.yaml
global:
  enabled: false
  datacenter: dc1
  name: consul
  image: hashicorp/consul-enterprise:1.21
  logLevel: debug
  tls:
    enabled: false
  acls:
    manageSystemACLs: false
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: key
  adminPartitions:
    enabled: true
    name: "k8s-east"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key

externalServers:
  enabled: true
  hosts: ['34.78.193.136']
  httpsPort: 8500

# DISABLE EVERYTHING that uses gRPC
connectInject:
  enabled: false
meshGateway:
  enabled: false
syncCatalog:
  enabled: false
dns:
  enabled: false

# Explicitly disable anything gRPC related
client:
  grpc: false
