apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: APIGateway
metadata:
  name: api-gateway
  namespace: default
spec:
  gatewayClassName: consul
  listeners:
    - name: http
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api-gateway.example.com
spec:
  selector:
    api-gateway.consul.hashicorp.com/name: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer