apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: development
spec:
  parentRefs:
    - name: api-gateway
      namespace: default
  hostnames:
    - "frontend.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: frontend
          port: 9090
---
apiVersion: mesh.consul.hashicorp.com/v2beta1  
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: development
spec:
  parentRefs:
    - name: api-gateway
      namespace: default
  hostnames:
    - "api.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api"
      backendRefs:
        - name: backend
          port: 9090
---
# Cross-partition route example
apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: HTTPRoute
metadata:
  name: cross-partition-route
  namespace: development
spec:
  parentRefs:
    - name: api-gateway
      namespace: default
  hostnames:
    - "west.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/west"
      backendRefs:
        - name: frontend
          namespace: development
          partition: k8s-west
          port: 9090