services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TERRAMINO_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 