---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "frontend"
        consul.hashicorp.com/connect-service-upstreams: "backend.production.k8s-west:9090"
        consul.hashicorp.com/service-tags: "k8s-east,development"
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: nicholasjackson/fake-service:v0.23.1
        ports:
        - containerPort: 9090
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:9090"
        - name: UPSTREAM_URIS
          value: "http://backend.virtual.production.ns.k8s-west.ap.gcp-dc1.dc.consul:9090"
        - name: MESSAGE
          value: "Hello from Frontend in k8s-east/development!"
        - name: NAME
          value: "frontend"
        - name: SERVER_TYPE
          value: "http"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: development
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  type: ClusterIP