apiVersion: v1
kind: Service
metadata:
  name: fake-service-backend
  namespace: development
  labels:
    app: fake-service-backend
spec:
  selector:
    app: fake-service-backend
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service-backend
  namespace: development
  labels:
    app: fake-service-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-service-backend
  template:
    metadata:
      labels:
        app: fake-service-backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-tags: "backend,fake-service"
        consul.hashicorp.com/service-meta-version: "v1.0.0"
        consul.hashicorp.com/service-meta-environment: "development"
    spec:
      containers:
      - name: fake-service
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - containerPort: 9090
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:9090"
        - name: NAME
          value: "Backend Service"
        - name: MESSAGE
          value: "Hello from Consul Admin Partitions Backend!"
        - name: SERVER_TYPE
          value: "http"
        - name: TIMING_50_PERCENTILE
          value: "30ms"
        - name: TIMING_90_PERCENTILE
          value: "60ms"
        - name: TIMING_99_PERCENTILE
          value: "90ms"
        - name: TIMING_VARIANCE
          value: "10"
        - name: HTTP_CLIENT_APPEND_REQUEST
          value: "true"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5