# Consul Enterprise Admin Partition Client Configuration for East Region
global:
  name: consul
  enabled: false
  image: hashicorp/consul-enterprise:${consul_version}
  imageEnvoy: envoyproxy/envoy:v1.30.7
  enableConsulNamespaces: true
  
  # Admin partition configuration
  adminPartitions:
    enabled: true
    name: "${partition_name}"
  
  # Enterprise license
  enterpriseLicense:
    secretName: consul-enterprise-license
    secretKey: key
  
  # TLS configuration
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
  
  # ACLs
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token
      secretKey: token

# External servers configuration (pointing to Consul server cluster)
externalServers:
  enabled: true
  hosts: ["${consul_server_ip}"]
  httpsPort: 8501
  grpcPort: 8502
  tlsServerName: "server.east.consul"
  k8sAuthMethodHost: "https://${k8s_api_endpoint}"

# Client configuration
client:
  enabled: true
  join: ["${consul_server_ip}"]
  
  # Resources
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# Server disabled (client-only cluster)
server:
  enabled: false

# UI disabled (use server cluster UI)
ui:
  enabled: false

# Connect inject
connectInject:
  enabled: true
  apiGateway:
    manageExternalCRDs: true
  consulNamespaces:
    mirroringK8S: true
  
  # Default injection annotations
  default: true
  
  # Resource defaults
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
      cpu: "50m"

# Controller for CRDs
controller:
  enabled: true

# Mesh gateway for cross-partition communication
meshGateway:
  enabled: true
  replicas: 1
  service:
    type: LoadBalancer
    ports:
      - port: 443
        nodePort: null
  
  # Resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Deprecated ingress gateways - use API Gateway instead
ingressGateways:
  enabled: false

# Terminating gateway for external services
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  gateways:
    - name: terminating-gateway

# Sync catalog disabled for admin partitions
syncCatalog:
  enabled: false

# DNS
dns:
  enabled: true

# Tests
tests:
  enabled: false