# Consul Enterprise Server Configuration for West Region
global:
  name: consul
  image: hashicorp/consul-enterprise:${consul_version}
  imageEnvoy: envoyproxy/envoy:v1.30.7
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
  datacenter: ${datacenter}
  
  # Enterprise license
  enterpriseLicense:
    secretName: consul-enterprise-license
    secretKey: key
  
  # Gossip encryption
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  
  # Modern TLS configuration
  tls:
    enabled: true
    httpsOnly: false
    enableAutoEncrypt: true
    verify: false
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-cert
      secretKey: tls.key
  
  # ACLs
  acls:
    manageSystemACLs: true

# Server configuration
server:
  enabled: true
  image: hashicorp/consul-enterprise:${consul_version}
  replicas: 3
  bootstrapExpected: 3
  
  # Storage
  storage: 10Gi
  storageClass: standard-rwo
  
  # Resources
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi" 
      cpu: "500m"
  
  # Anti-affinity to spread servers across nodes
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  
  # Expose servers via LoadBalancer for admin partition clients
  exposeService:
    enabled: true
    type: LoadBalancer
    annotations: |
      cloud.google.com/backend-config: '{"default": "consul-backend-config"}'
  
  # Extra configuration using modern format
  extraConfig: |
    {
      "log_level": "INFO",
      "server": true,
      "retry_join": ["provider=k8s label_selector=\"app=consul,component=server\""],
      "ui_config": {
        "enabled": true
      },
      "connect": {
        "enabled": true
      },
      "ports": {
        "grpc_tls": 8502
      }
    }

# Client disabled (server-only cluster)
client:
  enabled: false

# UI
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer

# Connect inject
connectInject:
  enabled: true
  apiGateway:
    manageExternalCRDs: true

# Controller
controller:
  enabled: false

# Mesh gateway for cross-partition communication
meshGateway:
  enabled: true
  replicas: 2
  service:
    type: LoadBalancer
    enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Deprecated ingress gateways - use API Gateway instead
ingressGateways:
  enabled: false

# Terminating gateway
terminatingGateways:
  enabled: false

# Sync catalog
syncCatalog:
  enabled: false

# DNS
dns:
  enabled: false

# Tests
tests:
  enabled: false